
import { useState } from 'react';
import Head from 'next/head'
import moment from "moment";
import "moment/locale/id";

export default function Home() {
  const today = moment().format("YYYYMMDD");
  const [currentDate, setCurrentDate] = useState(today);
  const getMonday = (date: any) => {
    return moment(date, "YYYYMMDD").startOf("week").day("Senin");
  };

  const addDay = (date: any, day: any) => {
    return moment(date, "YYYYMMDD").add(day, "d");
  };

  const subDay = (date: any, day: any) => {
    return moment(date, "YYYYMMDD").subtract(day, "d");
  };

  const addZero = (num: any) => {
    return num <= 9 ? `0${num}` : `${num}`;
  };

  const handleChangeDate = (date: any) => {
    setCurrentDate(date);
    //setVisible(false);
    //setListKey(listKey + 1);
  };


  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="px-6 py-3 text-center text-xs font-medium text-gray-500 tracking-wider">
        
        <div className="flex items-center justify-between py-2 px-6">
          <div className='border px-4 py-3 hover:bg-gray-100 rounded'>Today</div>
          <div className="border rounded-lg px-1 flex items-center">
            <button
              type="button"
              className="cursor-pointer leading-none rounded-lg transition ease-in-out duration-100 inline-flex cursor-pointer hover:bg-gray-200 p-1 items-center"
              onClick={() => handleChangeDate(subDay(currentDate, 7))}
            >
              <svg
                className="h-6 w-6 text-gray-500 inline-flex leading-none"
                fill="none"
                viewBox="0 0 24 24"
                stroke="currentColor"
              >
                <path
                  strokeLinecap="round"
                  strokeLinejoin="round"
                  strokeWidth="2"
                  d="M15 19l-7-7 7-7"
                />
              </svg>
            </button>
            <div className="border-r inline-flex h-6"></div>
            <div
              className="cursor-pointer ml-2 mr-2 text-sm font-bold text-gray-800"
            >
              {getMonday(currentDate).format("dddd, Do MMMM YYYY")} -{" "}
              {addDay(getMonday(currentDate), 6).format("dddd, Do MMMM YYYY")}
            </div>
            <div className="border-r inline-flex h-6"></div>
            <button
              type="button"
              className="cursor-pointer leading-none rounded-lg transition ease-in-out duration-100 inline-flex items-center cursor-pointer hover:bg-gray-200 p-1"
              onClick={() => handleChangeDate(addDay(currentDate, 7))}
            >
              <svg
                className="h-6 w-6 text-gray-500 inline-flex leading-none"
                fill="none"
                viewBox="0 0 24 24"
                stroke="currentColor"
              >
                <path
                  strokeLinecap="round"
                  strokeLinejoin="round"
                  strokeWidth="2"
                  d="M9 5l7 7-7 7"
                />
              </svg>
            </button>
          </div>
        </div>
      </div>
      <table className="min-w-full divide-y divide-gray-300">
        <thead className="bg-gray-50 text-xs">
          <tr>
            {[...Array(7)].map((x, i) => (
              <th
                key={i}
                className="px-6 py-3 text-center text-xs font-medium text-gray-500 uppercase tracking-wider"
              >
                {addDay(getMonday(currentDate), i).format(
                  "dddd, Do MMMM YYYY"
                )}
              </th>
            ))}
          </tr>
        </thead>
        <tbody>
          {[...Array(24)].map((x, hour) => (
            <tr key={hour}>
              {[...Array(7)].map((x, day) => (
              <td
                key={day}
                className="text-center text-xs font-medium text-gray-500 tracking-wider"
              >
                <div className='flex flex-row'>
                  <div className='px-6 py-3 '>{`${addZero(hour)}:00`}</div>
                  <div className='w-full text-white'>
                    <div
                      className='w-full px-6 py-3 hover:bg-teal-600 hover:text-white rounded'
                      onClick={() => alert("add jadwal")}
                    >(Tanpa judul)</div>
                  </div>
                </div>
              </td>
            ))}
            </tr>
          ))}
        </tbody>
      </table>      
    </>
  )
}
